### ISSUE TITLE
Release .net client abstractions

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/opensearch-net-abstractions#16]
Acceptance criteria
---------------------
- [ ] Nuget packages are available for download and use
- [x] https://github.com/opensearch-project/opensearch-net-abstractions/issues/8
- [x] .Net client tested with abstractions library once all PRs done

PR to complete
-----------------
- [x] https://github.com/opensearch-project/opensearch-net-abstractions/pull/17
- [x] https://github.com/opensearch-project/opensearch-net-abstractions/pull/18
- [x] https://github.com/opensearch-project/opensearch-net-abstractions/pull/19
- [x] https://github.com/opensearch-project/opensearch-net-abstractions/pull/15

Release Process
-----------------
https://github.com/opensearch-project/opensearch-net-abstractions/blob/main/RELEASING.md

- [ ] Release branch created for `1.0` release
- [ ] Release branch created for the next `1.x` release

**Comment by MaxKsyunz** [comment]
@Yury-Fridlyand, @wbeckler, what's the next step in getting this published? All the listed PRs are merged.

**Comment by Yury-Fridlyand** [comment]
> @Yury-Fridlyand, @wbeckler, what's the next step in getting this published? All the listed PRs are merged.

I'm going to test abstractions's `main` with https://github.com/opensearch-project/opensearch-net/pull/51 to ensure that everything is OK.

**Comment by Yury-Fridlyand** [comment]
All tests pass: https://github.com/Bit-Quill/opensearch-net/actions?query=branch%3Adev-os-2.0-integ-abstractions
![image](https://user-images.githubusercontent.com/88679692/187525370-717171cc-392d-4b5f-84fa-f60bde1b1d14.png)

**Comment by Yury-Fridlyand** [comment]
Since https://github.com/opensearch-project/opensearch-net/pull/92 already merged and .net client released v. [1.1.0](https://github.com/opensearch-project/opensearch-net/releases/tag/v1.1.0), it is not relevant anymore.
